name = "ExamplePackage"
uuid = "fa10b87b-3689-4d30-93b9-7e3992778ff1"
authors = ["Anirudh Praveen"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
